# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-10-12 12:36+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: davinci_helper/functions/gui/function_1_gui.py:152
msgid ""
"Check and install\n"
"missing dependencies"
msgstr ""

#: davinci_helper/functions/gui/function_1_gui.py:155
msgid ""
"This part of the software will install all the dependencies necessary to "
"correctly launch the installation and the execution of DaVinci Resolve. The "
"script will detect your Fedora version and the libraries installed, after "
"that it will install only the packages needed. This script does not collect "
"or diffuse any information about you or your system. The internet connection "
"is required only if there are any missing libraries to install."
msgstr ""

#. SETTING BUTTON TEXT LABEL
#: davinci_helper/functions/gui/function_1_gui.py:208
#: davinci_helper/functions/gui/function_1_gui.py:239
#: davinci_helper/functions/gui/function_2_gui.py:220
#: davinci_helper/functions/gui/function_2_gui.py:248
#: davinci_helper/functions/gui/function_3_gui.py:208
#: davinci_helper/functions/gui/function_3_gui.py:239
#: davinci_helper/functions/gui/function_4_gui.py:208
#: davinci_helper/functions/gui/function_4_gui.py:239 data/ui/function_1.ui:223
#: data/ui/function_2.ui:298 data/ui/function_3.ui:223
#: data/ui/function_4.ui:223
msgid "Show Info"
msgstr ""

#. SETTING BUTTON TEXT LABEL
#: davinci_helper/functions/gui/function_1_gui.py:211
#: davinci_helper/functions/gui/function_1_gui.py:489
#: davinci_helper/functions/gui/function_2_gui.py:601
#: davinci_helper/functions/gui/function_3_gui.py:211
#: davinci_helper/functions/gui/function_3_gui.py:497
#: davinci_helper/functions/gui/function_4_gui.py:211
#: davinci_helper/functions/gui/function_4_gui.py:489
#: davinci_helper/functions/gui/ffmpeg_install_gui.py:184
#: davinci_helper/functions/gui/ffmpeg_install_gui.py:437
#: davinci_helper/functions/gui/module_install_error_dialog_guy.py:158
#: data/ui/function_1.ui:522 data/ui/function_2.ui:597
#: data/ui/function_3.ui:522 data/ui/function_4.ui:522
#: data/ui/ffmpeg_install.ui:438 data/ui/module_install_error_dialog.ui:283
#: davinci_helper/functions/gui/ffmpeg_install_gui.py:186
#: davinci_helper/functions/gui/ffmpeg_install_gui.py:442
#: davinci_helper/functions/gui/module_install_error_dialog_guy.py:161
msgid "Show logs"
msgstr ""

#: davinci_helper/functions/gui/function_1_gui.py:247
#: davinci_helper/functions/gui/function_2_gui.py:256
#: davinci_helper/functions/gui/function_3_gui.py:247
#: davinci_helper/functions/gui/function_4_gui.py:247
msgid "Hide info"
msgstr ""

#: davinci_helper/functions/gui/function_1_gui.py:406
msgid "The dependencies have been correctly installed"
msgstr ""

#: davinci_helper/functions/gui/function_1_gui.py:409
msgid ""
"All the dependencies have been correctly installed inside the system.\n"
"Now you can correctly start the DaVinci Resolve installer."
msgstr ""

#: davinci_helper/functions/gui/function_1_gui.py:426
msgid "There was an error installing the dependencies"
msgstr ""

#: davinci_helper/functions/gui/function_1_gui.py:434
msgid ""
"There was an error getting what version of Fedora you are using.\n"
"Please check the logs to have more details."
msgstr ""

#: davinci_helper/functions/gui/function_1_gui.py:442
msgid ""
"There was an error getting the list of the installed libraries on your "
"system.\n"
"Please check the logs to have more details."
msgstr ""

#: davinci_helper/functions/gui/function_1_gui.py:450
msgid ""
"There was an error during the installation of the missing libraries.\n"
"Please check the logs to have more details."
msgstr ""

#: davinci_helper/functions/gui/function_1_gui.py:458
#: davinci_helper/functions/gui/function_3_gui.py:466
#: davinci_helper/functions/gui/function_4_gui.py:458
#: davinci_helper/functions/gui/ffmpeg_install_gui.py:406
#: davinci_helper/functions/gui/ffmpeg_install_gui.py:411
msgid "You need to be an admin to use this function"
msgstr ""

#: davinci_helper/functions/gui/function_1_gui.py:461
#: davinci_helper/functions/gui/function_3_gui.py:469
#: davinci_helper/functions/gui/function_4_gui.py:461
#: davinci_helper/functions/gui/ffmpeg_install_gui.py:409
#: davinci_helper/functions/gui/ffmpeg_install_gui.py:414
msgid ""
"It was impossible to start this function because you didn't give the "
"necessary root permission for his execution. Try again giving the root "
"permission."
msgstr ""

#: davinci_helper/functions/gui/function_1_gui.py:497
#: davinci_helper/functions/gui/function_2_gui.py:609
#: davinci_helper/functions/gui/function_3_gui.py:505
#: davinci_helper/functions/gui/function_4_gui.py:497
#: davinci_helper/functions/gui/ffmpeg_install_gui.py:445
#: davinci_helper/functions/gui/module_install_error_dialog_guy.py:166
#: davinci_helper/functions/gui/ffmpeg_install_gui.py:450
#: davinci_helper/functions/gui/module_install_error_dialog_guy.py:169
msgid "Hide logs"
msgstr ""

#: davinci_helper/functions/gui/loading_gui.py:92
msgid ""
"The time needed to complete this task will vary on your computer and network "
"performance."
msgstr ""

#: davinci_helper/functions/gui/start_screen_gui.py:151
msgid "Welcome to DaVinci Helper"
msgstr ""

#: davinci_helper/functions/gui/start_screen_gui.py:154
msgid "The best tool for managing DaVinci Resolve on Linux"
msgstr ""

#: davinci_helper/functions/gui/function_2_gui.py:159
msgid ""
"Launch DaVinci Resolve\n"
"installation wizard"
msgstr ""

#: davinci_helper/functions/gui/function_2_gui.py:162
msgid ""
"This part of the software will ask you to indicate the DaVinci Resolve "
"installer file path, then it will run it with the necessary patch to make it "
"launch properly."
msgstr ""

#: davinci_helper/functions/gui/function_2_gui.py:276
msgid "Select the DaVinci Resolve installer .zip file"
msgstr ""

#: davinci_helper/functions/gui/function_2_gui.py:536
msgid "You have successfully started the DaVinci wizard"
msgstr ""

#: davinci_helper/functions/gui/function_2_gui.py:539
msgid ""
"You have successfully started the DaVinci Resolve installation wizard.\n"
"Now you can install DaVinci Resolve on your computer."
msgstr ""

#: davinci_helper/functions/gui/function_2_gui.py:559
msgid "There was an error launching the DaVinci wizard"
msgstr ""

#: davinci_helper/functions/gui/function_2_gui.py:567
msgid ""
"There was an error extracting the DaVinci Resolve installer zip inside the "
"target folder.\n"
"Please check the logs to have more details."
msgstr ""

#: davinci_helper/functions/gui/function_2_gui.py:576
msgid ""
"There was an error launching the DaVinci Resolve installation wizard.\n"
"Please check the logs to have more details."
msgstr ""

#: davinci_helper/functions/gui/function_3_gui.py:152
msgid ""
"Apply the DaVinci Resolve\n"
"post installation fix"
msgstr ""

#: davinci_helper/functions/gui/function_3_gui.py:155
msgid ""
"This part of the software will put some of the dependencies shipped with "
"DaVinci Resolve in a safe folder, in order to make it use the system ones."
msgstr ""

#: davinci_helper/functions/gui/function_3_gui.py:406
msgid ""
"The post installation fix\n"
"has been correctly applied"
msgstr ""

#: davinci_helper/functions/gui/function_3_gui.py:409
msgid ""
"All the problematic libraries have been correctly moved inside the secure "
"folder.\n"
"Now you can correctly run DaVinci Resolve."
msgstr ""

#: davinci_helper/functions/gui/function_3_gui.py:426
msgid "There was an error applying the fixes"
msgstr ""

#: davinci_helper/functions/gui/function_3_gui.py:434
msgid ""
"There was an error finding the DaVinci Resolve installation folder.\n"
"Please check the logs to have more details."
msgstr ""

#: davinci_helper/functions/gui/function_3_gui.py:442
msgid ""
"There was an error finding a compatible version of DaVinci Resolve on your "
"system.\n"
"Please check the logs to have more details."
msgstr ""

#: davinci_helper/functions/gui/function_3_gui.py:450
msgid ""
"There was an error during the creation of the libraries' secure folder.\n"
"Please check the logs to have more details."
msgstr ""

#: davinci_helper/functions/gui/function_3_gui.py:458
msgid ""
"There was an error moving the libraries inside the secure folder.\n"
"Please check the logs to have more details."
msgstr ""

#: davinci_helper/functions/gui/function_4_gui.py:152
msgid ""
"Check and install the\n"
"correct gpu drivers"
msgstr ""

#: davinci_helper/functions/gui/function_4_gui.py:155
msgid ""
"This part of the software will check what GPU you are using and then, if it "
"is supported, it will check if the correct drivers are installed. If it "
"finds missing or outdated drivers the software will install them to make "
"your GPU fully support DaVinci Resolve."
msgstr ""

#: davinci_helper/functions/gui/function_4_gui.py:406
msgid "The GPUs drivers have been correctly installed"
msgstr ""

#: davinci_helper/functions/gui/function_4_gui.py:409
msgid ""
"All the GPUs drivers have been correctly installed inside the system.\n"
"Now you can correctly run DaVinci Resolve."
msgstr ""

#: davinci_helper/functions/gui/function_4_gui.py:426
msgid "There was an error installing the GPUs drivers"
msgstr ""

#: davinci_helper/functions/gui/function_4_gui.py:434
msgid ""
"There was an error finding a supported GPU inside your system.\n"
"Please check the logs to have more details."
msgstr ""

#: davinci_helper/functions/gui/function_4_gui.py:442
#: davinci_helper/functions/gui/ffmpeg_install_gui.py:382
#: davinci_helper/functions/gui/ffmpeg_install_gui.py:387
msgid ""
"There was an error while adding the RPM Fusion repository to your system.\n"
"Please check the logs to have more details."
msgstr ""

#: davinci_helper/functions/gui/function_4_gui.py:450
msgid ""
"There was an error during the installation of the GPUs drivers.\n"
"Please check the logs to have more details."
msgstr ""

#: davinci_helper/functions/gui/file_error_dialog_gui.py:92
#: davinci_helper/functions/gui/file_error_dialog_gui.py:95
msgid "Select a valid file !"
msgstr ""

#: davinci_helper/functions/gui/file_error_dialog_gui.py:98
#: davinci_helper/functions/gui/file_error_dialog_gui.py:101
msgid ""
"It seems like you didn't load any file.\n"
"Please load a valid DaVinci Resolve installer zip file to continue."
msgstr ""

#: davinci_helper/functions/gui/file_error_dialog_gui.py:103
#: davinci_helper/functions/gui/file_error_dialog_gui.py:106
msgid ""
"It seems like you tried to load an usupported file.\n"
"Please load a valid DaVinci Resolve installer zip file to continue.\n"
"If you have renamed it, remember that the file name must\n"
"contain the words 'DaVinci', 'Resolve', 'Linux' inside of it\n"
"and it must to have the '.zip' extension."
msgstr ""

#: davinci_helper/functions/gui/welcome_dialog_gui.py:111
#: davinci_helper/functions/gui/welcome_dialog_gui.py:114
msgid ""
"Thank you for installing\n"
"DaVinci Helper"
msgstr ""

#: davinci_helper/functions/gui/welcome_dialog_gui.py:120
#: davinci_helper/functions/gui/welcome_dialog_gui.py:123
msgid ""
"If you find this app useful and want to improve it please consider helping "
"us <a href=\"https://github.com/H3rz3n/davinci-helper\">developing</a> this "
"app or <a href=\"https://www.paypal.com/donate/?"
"hosted_button_id=CPCG2RFAV82T8\">making a donation</a>  to the project."
msgstr ""

#: davinci_helper/functions/gui/welcome_dialog_gui.py:124
#: davinci_helper/functions/gui/welcome_dialog_gui.py:127
msgid "Don't show again"
msgstr ""

#: davinci_helper/functions/gui/settings_management_dialog_gui.py:95
#: davinci_helper/functions/gui/settings_management_dialog_gui.py:98
msgid "Settings restored successfully"
msgstr ""

#: davinci_helper/functions/gui/settings_management_dialog_gui.py:98
#: davinci_helper/functions/gui/settings_management_dialog_gui.py:101
msgid ""
"The default app settings have been restored successfully.\n"
"If you are still experiencing any error or bug,\n"
"please contact us on the <a href=\"https://github.com/H3rz3n/davinci-helper/"
"issues\">project GitHub page</a>"
msgstr ""

#: davinci_helper/functions/gui/check_update_dialog_gui.py:101
#: davinci_helper/functions/gui/check_update_dialog_gui.py:104
msgid "A new update is available"
msgstr ""

#: davinci_helper/functions/gui/check_update_dialog_gui.py:104
#: davinci_helper/functions/gui/check_update_dialog_gui.py:107
msgid ""
"A new version of this app has been found.\n"
"We recommend you to update it before continue using it."
msgstr ""

#: davinci_helper/functions/gui/function_5_gui.py:167
#: davinci_helper/main.py:353
msgid "DaVinci Video Converter"
msgstr ""

#: davinci_helper/functions/gui/function_5_gui.py:170
msgid "Exported video settings"
msgstr ""

#: davinci_helper/functions/gui/function_5_gui.py:195
msgid ""
"The time needed to complete this task will vary\n"
"on your computer and network performance."
msgstr ""

#: davinci_helper/functions/gui/function_5_gui.py:298
msgid "Select the converted video output folder"
msgstr ""

#: davinci_helper/functions/gui/function_5_gui.py:355
msgid "Select the files to convert"
msgstr ""

#: davinci_helper/functions/gui/function_5_gui.py:914
#, python-brace-format
msgid "Converting the file : {self.file_name}"
msgstr ""

#: davinci_helper/functions/gui/function_5_gui.py:955
#, python-brace-format
msgid "Finished processing the file : {self.file_name}"
msgstr ""

#: davinci_helper/functions/gui/function_5_gui.py:961
#, python-brace-format
msgid "{self.file_name} - 100%"
msgstr ""

#: davinci_helper/functions/gui/function_5_gui.py:1014
msgid "{self.file_name} - {progress * 100:.2f}%"
msgstr ""

#: davinci_helper/functions/gui/function_5_gui.py:1032
msgid "Starting with the next file..."
msgstr ""

#: davinci_helper/functions/gui/ffmpeg_install_gui.py:140
#: davinci_helper/functions/gui/ffmpeg_install_gui.py:142
msgid ""
"Install FFMPEG\n"
"to use this feature"
msgstr ""

#: davinci_helper/functions/gui/ffmpeg_install_gui.py:342
#: davinci_helper/functions/gui/ffmpeg_install_gui.py:347
msgid "FFMPEG was successfully installed"
msgstr ""

#: davinci_helper/functions/gui/ffmpeg_install_gui.py:345
#: davinci_helper/functions/gui/ffmpeg_install_gui.py:350
msgid ""
"FFMPEG has been correctly installed inside the system.\n"
"Now you can start using DaVinci Video Convert."
msgstr ""

#: davinci_helper/functions/gui/ffmpeg_install_gui.py:368
#: davinci_helper/functions/gui/ffmpeg_install_gui.py:373
msgid "There was an error installing FFMPEG"
msgstr ""

#: davinci_helper/functions/gui/ffmpeg_install_gui.py:390
#: davinci_helper/functions/gui/ffmpeg_install_gui.py:395
msgid ""
"There was an error installing FFMPEG from the RPM Fusion repository.\n"
"Please check the logs to have more details."
msgstr ""

#: davinci_helper/functions/gui/ffmpeg_install_gui.py:398
#: davinci_helper/functions/gui/ffmpeg_install_gui.py:403
msgid ""
"There was an error swapping FFMPEG lite with\n"
"FFMPEG full from the RPM Fusion repository.\n"
"Please check the logs to have more details."
msgstr ""

#: davinci_helper/functions/gui/file_size_warning_dialog_gui.py:101
#: davinci_helper/functions/gui/file_size_warning_dialog_gui.py:104
msgid "This will need a lot of space !"
msgstr ""

#: davinci_helper/functions/gui/file_size_warning_dialog_gui.py:104
#: davinci_helper/functions/gui/file_size_warning_dialog_gui.py:107
msgid ""
"The conversion of the files using the DNxHD/HR encoder will make new files "
"fully compatible with DaVinci Resolve Free.\n"
"\n"
"The use of these uncompressed sources will make your editing experience "
"faster, but it will take a lot of disk space.\n"
msgstr ""

#: davinci_helper/functions/gui/file_size_warning_dialog_gui.py:107
#: davinci_helper/functions/gui/file_size_warning_dialog_gui.py:110
#, python-brace-format
msgid ""
"The estimated disk space needed to convert the files is :\n"
"{space_placeholder}\n"
msgstr ""

#: davinci_helper/functions/gui/file_size_warning_dialog_gui.py:110
#: davinci_helper/functions/gui/file_size_warning_dialog_gui.py:113
msgid ""
"If you want to use less disk space please consider using\n"
"lower video and audio settings."
msgstr ""

#: davinci_helper/functions/gui/module_install_error_dialog_guy.py:104
#: davinci_helper/functions/gui/module_install_error_dialog_guy.py:107
msgid "There are some missing modules"
msgstr ""

#: davinci_helper/functions/gui/module_install_error_dialog_guy.py:107
#: davinci_helper/functions/gui/module_install_error_dialog_guy.py:110
msgid ""
"There was an error installing the Moviepy python module.\n"
"Please check the logs to have more details."
msgstr ""

#: davinci_helper/functions/gui/converter_dialog_gui.py:98
#: davinci_helper/functions/gui/converter_dialog_gui.py:101
msgid "Select a valid file"
msgstr ""

#: davinci_helper/functions/gui/converter_dialog_gui.py:101
#: davinci_helper/functions/gui/converter_dialog_gui.py:104
msgid ""
"It seems like you didn't load any file to convert.\n"
"\n"
"Please load at least one supported video file to continue."
msgstr ""

#: davinci_helper/functions/gui/converter_dialog_gui.py:112
#: davinci_helper/functions/gui/converter_dialog_gui.py:115
msgid "Select a valid file and output folder"
msgstr ""

#: davinci_helper/functions/gui/converter_dialog_gui.py:115
#: davinci_helper/functions/gui/converter_dialog_gui.py:118
msgid ""
"It seems like you didn't load any file to convert\n"
"and you didn't choose any output folder.\n"
"\n"
"Please load at least one supported video file\n"
"and select a valid output folder to continue."
msgstr ""

#: davinci_helper/functions/gui/converter_dialog_gui.py:125
#: davinci_helper/functions/gui/converter_dialog_gui.py:128
msgid "Select a valid output folder"
msgstr ""

#: davinci_helper/functions/gui/converter_dialog_gui.py:128
#: davinci_helper/functions/gui/converter_dialog_gui.py:131
msgid ""
"It seems like you didn't load any output folder.\n"
"\n"
"Please select a valid output folder to continue."
msgstr ""

#: davinci_helper/functions/gui/converter_dialog_gui.py:138
#: davinci_helper/functions/gui/converter_dialog_gui.py:141
msgid "Unsupported files found"
msgstr ""

#: davinci_helper/functions/gui/converter_dialog_gui.py:141
#: davinci_helper/functions/gui/converter_dialog_gui.py:144
msgid ""
"Some files can't be converted because they are unsupported.\n"
"If you decide to continue, the following file will not be converted :\n"
msgstr ""

#. SETTING BUTTON TEXT LABEL
#: davinci_helper/functions/gui/converter_dialog_gui.py:156
#: data/ui/file_size_warning_dialog.ui:254
#: davinci_helper/functions/gui/converter_dialog_gui.py:159
msgid "Continue"
msgstr ""

#: davinci_helper/functions/gui/converter_dialog_gui.py:169
#: davinci_helper/functions/gui/converter_dialog_gui.py:172
msgid "All the files have been converted"
msgstr ""

#: davinci_helper/functions/gui/converter_dialog_gui.py:172
#: davinci_helper/functions/gui/converter_dialog_gui.py:175
msgid ""
"All your files have been correctly converted\n"
"and placed inside your designed folder."
msgstr ""

#: davinci_helper/functions/gui/converter_dialog_gui.py:182
#: davinci_helper/functions/gui/converter_dialog_gui.py:185
msgid "Are you sure you want to exit ?"
msgstr ""

#: davinci_helper/functions/gui/converter_dialog_gui.py:185
#: davinci_helper/functions/gui/converter_dialog_gui.py:188
msgid ""
"The video conversion is still going on,\n"
"if you exit this app the process will be interupted and\n"
"you will get only the files converted\n"
"before the app closure."
msgstr ""

#: davinci_helper/functions/gui/converter_dialog_gui.py:188
#: davinci_helper/functions/gui/converter_dialog_gui.py:191
msgid "Continue conversion"
msgstr ""

#: davinci_helper/functions/gui/converter_dialog_gui.py:194
#: davinci_helper/functions/gui/converter_dialog_gui.py:197
msgid "Exit app"
msgstr ""

#: davinci_helper/functions/logic/function_1.py:57
msgid ""
"DEBUG : There was an error reading what version of Fedora is installed :"
msgstr ""

#: davinci_helper/functions/logic/function_1.py:61
#: davinci_helper/functions/logic/function_1.py:92
#: davinci_helper/functions/logic/function_1.py:177
#: davinci_helper/functions/logic/function_2.py:74
#: davinci_helper/functions/logic/function_2.py:91
#: davinci_helper/functions/logic/function_3.py:58
#: davinci_helper/functions/logic/function_3.py:165
#: davinci_helper/functions/logic/function_3.py:184
#: davinci_helper/functions/logic/function_4.py:385
#: davinci_helper/functions/logic/function_4.py:459
#: davinci_helper/functions/logic/function_4.py:507
#: davinci_helper/functions/logic/function_4.py:535
#: davinci_helper/functions/logic/install_ffmpeg.py:104
#: davinci_helper/functions/logic/install_ffmpeg.py:138
#: davinci_helper/functions/logic/install_ffmpeg.py:175
#: davinci_helper/functions/logic/install_python_modules.py:92
#: davinci_helper/functions/logic/function_1.py:84
#: davinci_helper/functions/logic/function_1.py:115
#: davinci_helper/functions/logic/function_1.py:257
#: davinci_helper/functions/logic/function_2.py:94
msgid ""
"Please open an issue report and paste this error code on the project GitHub "
"page :"
msgstr ""

#: davinci_helper/functions/logic/function_1.py:89
#: davinci_helper/functions/logic/function_1.py:112
msgid "DEBUG : There was an error reading the library list :"
msgstr ""

#: davinci_helper/functions/logic/function_1.py:141
#: davinci_helper/functions/logic/function_1.py:164
#: davinci_helper/functions/logic/function_1.py:220
msgid "The following libraries will be installed because they are missing :"
msgstr ""

#: davinci_helper/functions/logic/function_1.py:151
#: davinci_helper/functions/logic/function_1.py:174
#: davinci_helper/functions/logic/function_1.py:230
msgid ""
"There are no missing libraries to install, you can now install DaVinci "
"Resolve"
msgstr ""

#: davinci_helper/functions/logic/function_1.py:173
#: davinci_helper/functions/logic/function_1.py:253
msgid "DEBUG : There was an error installing the missing libraries :"
msgstr ""

#: davinci_helper/functions/logic/function_2.py:71
msgid "DEBUG : There was an error extracting the DaVinci Resolve installer :"
msgstr ""

#: davinci_helper/functions/logic/function_2.py:88
#: davinci_helper/functions/logic/function_2.py:91
msgid ""
"DEBUG : There was an error launching the DaVinci Resolve installation "
"wizard :"
msgstr ""

#: davinci_helper/functions/logic/function_3.py:55
msgid ""
"DEBUG : It was impossible to find the DaVinci Resolve installation folder "
"in /opt/resolve."
msgstr ""

#: davinci_helper/functions/logic/function_3.py:56
msgid ""
"If you haven't done it already, please install DaVinci Resolve and try again."
msgstr ""

#: davinci_helper/functions/logic/function_3.py:75
msgid "DaVinci Resolve 18.x.x was found in the system"
msgstr ""

#: davinci_helper/functions/logic/function_3.py:85
msgid "DaVinci Resolve 19.x.x was found in the system"
msgstr ""

#: davinci_helper/functions/logic/function_3.py:94
msgid ""
"DEBUG : An installed version of DaVinci that is not currently supported was "
"found."
msgstr ""

#: davinci_helper/functions/logic/function_3.py:95
msgid ""
"Please visit the GitHub page to find which version of DaVinci Resolve are "
"supported."
msgstr ""

#: davinci_helper/functions/logic/function_3.py:139
msgid ""
"The libraries were already moved inside the secure folder. There was no need "
"to do anything."
msgstr ""

#: davinci_helper/functions/logic/function_3.py:149
msgid "The following libraries will be moved in a secure folder :"
msgstr ""

#: davinci_helper/functions/logic/function_3.py:162
msgid ""
"DEBUG : It was impossible to create the secure folder where to move the "
"libraries in /opt/resolve/libs/disabled_libraries."
msgstr ""

#: davinci_helper/functions/logic/function_3.py:163
msgid "Try again granting the app root permission or create it by yourself."
msgstr ""

#: davinci_helper/functions/logic/function_3.py:182
msgid ""
"DEBUG : There was an error moving the libraries inside the secure folder in /"
"opt/resolve/libs/disabled_libraries. Try again granting the app root "
"permission or move it by yourself."
msgstr ""

#: davinci_helper/functions/logic/function_3.py:195
msgid "The libraries were correctly moved inside the secure folder."
msgstr ""

#: davinci_helper/functions/logic/function_4.py:208
#, python-brace-format
msgid "A compatible Nvidia GPU was found : {gpu_name_placeholder}"
msgstr ""

#: davinci_helper/functions/logic/function_4.py:259
#, python-brace-format
msgid "A compatible AMD GPU was found : {gpu_name_placeholder}"
msgstr ""

#: davinci_helper/functions/logic/function_4.py:312
#, python-brace-format
msgid "A compatible Intel GPU was found : {gpu_name_placeholder}"
msgstr ""

#: davinci_helper/functions/logic/function_4.py:342
msgid "DEBUG : No supported GPU has been found inside your system."
msgstr ""

#: davinci_helper/functions/logic/function_4.py:343
msgid "If you know that you have a DaVinci Resolve compatible GPU,"
msgstr ""

#: davinci_helper/functions/logic/function_4.py:344
msgid ""
"please open an issue and paste this error code on the project GitHub page :"
msgstr ""

#: davinci_helper/functions/logic/function_4.py:368
#: davinci_helper/functions/logic/install_ffmpeg.py:87
msgid ""
"The RPM Fusion repository had already been added to the system, there was no "
"need to add it."
msgstr ""

#: davinci_helper/functions/logic/function_4.py:380
#: davinci_helper/functions/logic/install_ffmpeg.py:99
msgid ""
"DEBUG : It was impossible to add the RPM Fusion Free and Non-Free repository."
msgstr ""

#: davinci_helper/functions/logic/function_4.py:381
#: davinci_helper/functions/logic/install_ffmpeg.py:100
msgid "Check your network connection and try again or add it by yourself."
msgstr ""

#: davinci_helper/functions/logic/function_4.py:394
#: davinci_helper/functions/logic/install_ffmpeg.py:113
msgid ""
"The RPM Fusion Free and Non-Free repository have been successfully added."
msgstr ""

#: davinci_helper/functions/logic/function_4.py:442
msgid ""
"The proprietary Nvidia GPU driver was already installed on the system, there "
"was no need to install it."
msgstr ""

#: davinci_helper/functions/logic/function_4.py:454
msgid "DEBUG : It was impossible to install the proprietary Nvidia GPU driver."
msgstr ""

#: davinci_helper/functions/logic/function_4.py:455
#: davinci_helper/functions/logic/function_4.py:503
#: davinci_helper/functions/logic/function_4.py:531
msgid "Check your network connection and try again or install it by yourself."
msgstr ""

#: davinci_helper/functions/logic/function_4.py:467
msgid "The proprietary Nvidia GPU driver has been successfully installed."
msgstr ""

#: davinci_helper/functions/logic/function_4.py:490
msgid ""
"The open source AMD GPU driver was already installed on the system, there "
"was no need to install it."
msgstr ""

#: davinci_helper/functions/logic/function_4.py:502
#: davinci_helper/functions/logic/function_4.py:530
msgid "DEBUG : It was impossible to install the open source AMD GPU driver."
msgstr ""

#: davinci_helper/functions/logic/function_4.py:518
msgid ""
"The MESA Freeworld drivers were already installed on the system, there was "
"no need to install it."
msgstr ""

#: davinci_helper/functions/logic/function_4.py:543
msgid "The open source AMD GPU driver has been successfully installed."
msgstr ""

#: davinci_helper/functions/logic/function_4.py:560
msgid ""
"DEBUG : It was impossible to install the drivers for your GPU because it is "
"currently not supported by this app. "
msgstr ""

#: davinci_helper/functions/logic/function_4.py:562
msgid ""
"If you know that your GPU is supported by DaVinci Resolve please open an "
"issue report on the project GitHub page :"
msgstr ""

#: davinci_helper/functions/logic/install_ffmpeg.py:134
msgid "DEBUG : It was impossible to install FFMPEG from RPM Fusion."
msgstr ""

#: davinci_helper/functions/logic/install_ffmpeg.py:147
msgid ""
"FFMPEG was successfully installed from RPM Fusion. Now you can use DaVinci "
"Converter "
msgstr ""

#: davinci_helper/functions/logic/install_ffmpeg.py:171
msgid ""
"DEBUG : It was impossible to swap the lite version FFMPEG with the one from "
"RPM Fusion."
msgstr ""

#: davinci_helper/functions/logic/install_ffmpeg.py:184
msgid ""
"FFMPEG lite was successfully swapped with FFMPEG full from RPM Fusion. Now "
"you can use DaVinci Converter "
msgstr ""

#: davinci_helper/functions/logic/install_ffmpeg.py:289
#: davinci_helper/functions/logic/install_ffmpeg.py:241
msgid ""
"FFMPEG was already installed on the system\n"
"there was no need to install it."
msgstr ""

#: davinci_helper/functions/logic/install_python_modules.py:63
msgid ""
"Moviepy python module was already installed. There was no need to install it "
msgstr ""

#: davinci_helper/functions/logic/install_python_modules.py:88
msgid "DEBUG : It was impossible to install the python module moviepy."
msgstr ""

#: davinci_helper/functions/logic/install_python_modules.py:101
msgid ""
"Moviepy python module was successfully installed. Now you can use DaVinci "
"Converter "
msgstr ""

#: davinci_helper/main.py:341
msgid "Install missing dependencies"
msgstr ""

#: davinci_helper/main.py:344
msgid "Launch DaVinci Resolve installer"
msgstr ""

#: davinci_helper/main.py:347
msgid "Apply post installation fix"
msgstr ""

#: davinci_helper/main.py:350
msgid "Check and install GPU drivers"
msgstr ""

#.
#. WINDOW SECTION TITLE
#: data/desktop/com.davinci.helper.app.desktop:5
#: data/desktop/com.davinci.helper.app.metainfo.xml:17 data/ui/main.ui:48
#: data/desktop/com.davinci.helper.app.metainfo.xml:13
msgid "DaVinci Helper"
msgstr ""

#: data/desktop/com.davinci.helper.app.desktop:11
msgid "Video;Editing;DaVinci;Resolve"
msgstr ""

#.
#: data/desktop/com.davinci.helper.app.metainfo.xml:21
#: data/desktop/com.davinci.helper.app.metainfo.xml:16
msgid "The best DaVinci Resolve companion app on Linux"
msgstr ""

#: data/desktop/com.davinci.helper.app.metainfo.xml:29
#: data/desktop/com.davinci.helper.app.metainfo.xml:23
msgid ""
"This app is created with the purpose of making it easier for Linux users to "
"install and use DaVinci Resolve."
msgstr ""

#: data/desktop/com.davinci.helper.app.metainfo.xml:30
#: data/desktop/com.davinci.helper.app.metainfo.xml:24
msgid "Features :"
msgstr ""

#: data/desktop/com.davinci.helper.app.metainfo.xml:32
#: data/desktop/com.davinci.helper.app.metainfo.xml:26
msgid "Automatic and dynamic dependecies installation"
msgstr ""

#: data/desktop/com.davinci.helper.app.metainfo.xml:33
#: data/desktop/com.davinci.helper.app.metainfo.xml:27
msgid "DaVinci Resolve installation wizard easy start"
msgstr ""

#: data/desktop/com.davinci.helper.app.metainfo.xml:34
#: data/desktop/com.davinci.helper.app.metainfo.xml:28
msgid "Application of post install patch"
msgstr ""

#: data/desktop/com.davinci.helper.app.metainfo.xml:35
#: data/desktop/com.davinci.helper.app.metainfo.xml:29
msgid "Easy GPU Driver installation"
msgstr ""

#.
#: data/desktop/com.davinci.helper.app.metainfo.xml:51
#: data/desktop/com.davinci.helper.app.metainfo.xml:42
msgid "Lorenzo Maiuri"
msgstr ""

#: data/desktop/com.davinci.helper.app.metainfo.xml:94
#: data/desktop/com.davinci.helper.app.metainfo.xml:79
msgid "Brand new UI based on Adwaita"
msgstr ""

#: data/desktop/com.davinci.helper.app.metainfo.xml:95
#: data/desktop/com.davinci.helper.app.metainfo.xml:80
msgid "Added support for video conversion"
msgstr ""

#: data/desktop/com.davinci.helper.app.metainfo.xml:96
#: data/desktop/com.davinci.helper.app.metainfo.xml:81
msgid "Improved support for AMD GPUs"
msgstr ""

#: data/desktop/com.davinci.helper.app.metainfo.xml:97
#: data/desktop/com.davinci.helper.app.metainfo.xml:82
msgid "Added light theme and theme switch"
msgstr ""

#: data/desktop/com.davinci.helper.app.metainfo.xml:98
#: data/desktop/com.davinci.helper.app.metainfo.xml:83
msgid "Improved performance"
msgstr ""

#: data/desktop/com.davinci.helper.app.metainfo.xml:108
#: data/desktop/com.davinci.helper.app.metainfo.xml:92
#: data/desktop/com.davinci.helper.app.metainfo.xml:98
msgid "Added support for AMD GPUs."
msgstr ""

#: data/desktop/com.davinci.helper.app.metainfo.xml:116
#: data/desktop/com.davinci.helper.app.metainfo.xml:112
msgid "Switched to GPL-3.0 license"
msgstr ""

#: data/desktop/com.davinci.helper.app.metainfo.xml:122
#: data/desktop/com.davinci.helper.app.metainfo.xml:126
msgid "Initial release of DaVinci Helper."
msgstr ""

#. WINDOW SECTION TITLE
#: data/ui/main.ui:387
msgid "Hi"
msgstr ""

#. ITEM NAME
#: data/ui/main.ui:771
msgid "Load default settings"
msgstr ""

#. ITEM NAME
#: data/ui/main.ui:791
msgid "About this app"
msgstr ""

#. SETTING BUTTON TEXT LABEL
#: data/ui/function_1.ui:202 data/ui/function_2.ui:277
#: data/ui/function_3.ui:202 data/ui/function_4.ui:202
msgid "Start"
msgstr ""

#. SETTING BUTTON TEXT LABEL
#: data/ui/function_1.ui:501 data/ui/function_2.ui:576
#: data/ui/function_3.ui:501 data/ui/function_4.ui:501
#: data/ui/ffmpeg_install.ui:417
msgid "Start again"
msgstr ""

#. SETTING BUTTON TEXT LABEL
#: data/ui/file_error_dialog.ui:203 data/ui/welcome_dialog.ui:297
#: data/ui/setting_management_dialog.ui:203 data/ui/check_update_dialog.ui:270
#: data/ui/module_install_error_dialog.ui:262 data/ui/converter_dialog.ui:203
#: data/ui/converter_dialog.ui:227 data/ui/welcome_dialog.ui:294
#: data/ui/check_update_dialog.ui:267
msgid "Close"
msgstr ""

#. SETTING BUTTON TEXT LABEL
#: data/ui/check_update_dialog.ui:248 data/ui/check_update_dialog.ui:245
msgid "Download"
msgstr ""

#. SETTING THE TEXT
#: data/ui/function_5.ui:247
msgid "Video quality"
msgstr ""

#: data/ui/function_5.ui:273 data/ui/function_5.ui:339
msgid "Original"
msgstr ""

#: data/ui/function_5.ui:274 data/ui/function_5.ui:340
msgid "High"
msgstr ""

#: data/ui/function_5.ui:275 data/ui/function_5.ui:341
msgid "Medium"
msgstr ""

#: data/ui/function_5.ui:276 data/ui/function_5.ui:342
msgid "Low"
msgstr ""

#. SETTING THE TEXT
#: data/ui/function_5.ui:313
msgid "Audio quality"
msgstr ""

#. SETTING BUTTON TEXT LABEL
#: data/ui/function_5.ui:462
msgid "Convert"
msgstr ""

#. SETTING BUTTON TEXT LABEL
#: data/ui/function_5.ui:483
msgid "Load files"
msgstr ""

#. SETTING BUTTON TEXT LABEL
#: data/ui/function_5.ui:503
msgid "Clean list"
msgstr ""

#. SETTING BUTTON TEXT LABEL
#: data/ui/ffmpeg_install.ui:138
msgid "Install"
msgstr ""

#. SETTING BUTTON TEXT LABEL
#: data/ui/file_size_warning_dialog.ui:275
msgid "Cancel"
msgstr ""

#: davinci_helper/functions/gui/welcome_dialog_gui.py:117
msgid ""
"Thank you for trusting us and installing DaVinci Helper. We hope that this "
"app will make the management of DaVinci Resolve easier for you.\n"
msgstr ""

#: davinci_helper/functions/gui/welcome_dialog_gui.py:120
msgid ""
"This app is not affiliated in any way with BlackMagic Design, it's only a "
"community project and comes without any guarantees.\n"
msgstr ""

#: davinci_helper/functions/gui/function_5_gui.py:298
msgid "Select the converted videos output folder"
msgstr ""

#: davinci_helper/functions/logic/function_1.py:57
#: davinci_helper/functions/logic/function_1.py:65
#: davinci_helper/functions/logic/function_1.py:74
#, python-brace-format
msgid "You are using a supported OS version : {os_version_placeholder}"
msgstr ""

#: davinci_helper/functions/logic/function_1.py:80
msgid "DEBUG : There was an error reading what OS is installed :"
msgstr ""
